#!/usr/bin/env bash

if [[ -z $1 ]]; then
    echo "Need parameter for project to open"
    exit
fi

projectName="${1/\./_}"
projectDir=${1%/}
project=${projectName%/}
projectPath="$HOME/sources/$projectDir/"

if ! [[ -d "$projectPath" ]]; then
    echo "$1 is not a project directory"
    exit
fi

echo "$project"
if ! tmux has-session -t "$project" 2>/dev/null; then
    tmux new -d -s "$project" -c "$projectPath">/dev/null
    tmux splitw -v -p 20 -t "$project":1.1 -c "$projectPath"
    if [[ -f "$projectPath/flake.nix" ]]; then
        tmux send-keys -t "$project":1.1 'exec nix develop -c nvim' Enter
        tmux send-keys -t "$project":1.2 'exec nix develop' Enter
        sleep 1
        tmux send-keys -t "$project":1.1 Space '-'
    else
        tmux send-keys -t "$project":1.1 'v' Enter Space '-'
    fi
    tmux send-keys -t "$project":1.2 'clear' Enter
    tmux select-pane -t "$project":1.1
fi

if [[ -z $TMUX ]]; then
    tmux a -t "$project";
else
    tmux switch -t "$project";
fi
