#!/usr/bin/env bash

if ! tmux has-session -t main 2>/dev/null; then
	tmux new -d -s main -c ~/ >/dev/null
fi

if ! tmux has-session -t nixconfig 2>/dev/null; then
	tmux new -d -s nixconfig -c ~/.dotfiles/ >/dev/null
	tmux splitw -v -p 10 -t nixconfig:1.1 -c ~/.dotfiles/
	tmux select-pane -t nixconfig:1.2
	tmux select-pane -t nixconfig:1.1
	tmux send-keys -t nixconfig:1.1 'v flake.nix' Enter
fi

if ! tmux has-session -t nvimconfig 2>/dev/null; then
	tmux new -d -s nvimconfig -c ~/.config/nvim/ >/dev/null
	tmux send-keys -t nvimconfig:1 'v init.lua' Enter
fi

tmux a -t main
