#!/usr/bin/env bash

# WAYBAR_PID=$(pidof waybar)

# if [ -n "$WAYBAR_PID" ]; then
#     kill "$WAYBAR_PID"
# else
#     waybar &
# fi
state_file="/tmp/waybar-hidden"

if [[ -f "$state_file" ]]; then
  rm "$state_file"
else
  touch "$state_file"
fi

pkill -SIGRTMIN+8 waybar
